# # Use OpenJDK 17 slim as base
# FROM openjdk:21-jdk-slim

# # Set working directory
# WORKDIR /app

# # Copy built JAR into container
# COPY target/chatApp-0.0.1-SNAPSHOT.jar app.jar

# # Expose port 8080
# EXPOSE 8080

# # Command to run the JAR
# ENTRYPOINT ["java", "-jar", "app.jar"]



# Use OpenJDK 21
FROM openjdk:21-jdk-slim

WORKDIR /app

# Copy your built JAR
COPY target/chatApp-0.0.1-SNAPSHOT.jar app.jar

# Expose port
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]